<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ElectricianSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $electricians = [
            [
                "name" => "Aris Wibowo",
                "employee_id" => "60000040",
                "email" => "aris_wibowo@gmail.com",
                "department_id" => 1,
                "position_id" => 5,
            ],
            [
                "name" => "Wandi Sadeli Putra",
                "employee_id" => "31100056",
                "email" => "wandi@gmail.com",
                "department_id" => 1,
                "position_id" => 4,
            ],
            [
                "name" => "Achmad Yuprizal",
                "employee_id" => "31901010",
                "email" => "achmad_yuprizal@gmail.com",
                "department_id" => 1,
                "position_id" => 3,
            ],
            [
                "name" => "Chaerul Umam",
                "employee_id" => "31810020",
                "email" => "chaerul_umam@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Leonardus D N",
                "employee_id" => "31908024",
                "email" => "leonardus_d_n@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Kusmantoro",
                "employee_id" => "32100027",
                "email" => "kusmantoro@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Whisnu Eko P",
                "employee_id" => "55000066",
                "email" => "whisnu_eko_p@gmail.com",
                "department_id" => 1,
                "position_id" => 1,
            ],
            [
                "name" => "Andriyanto",
                "employee_id" => "55000149",
                "email" => "andriyanto1@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Eko Nugroho",
                "employee_id" => "31100011",
                "email" => "eko_nugroho@gmail.com",
                "department_id" => 1,
                "position_id" => 3,
            ],
            [
                "name" => "Edi Dwitanto",
                "employee_id" => "55000108",
                "email" => "edi_dwitanto@gmail.com",
                "department_id" => 1,
                "position_id" => 1,
            ],
            [
                "name" => "Imam Achmad Azhari",
                "employee_id" => "31708012",
                "email" => "imam_achmad_azhari@gmail.com",
                "department_id" => 1,
                "position_id" => 3,
            ],
            [
                "name" => "Riki Arliandi",
                "employee_id" => "31100033",
                "email" => "riki_arliandi@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Herianto As Purba",
                "employee_id" => "31909001",
                "email" => "herianto_as_purba@gmail.com",
                "department_id" => 1,
                "position_id" => 4,
            ],
            [
                "name" => "Kukuh Budi",
                "employee_id" => "31904009",
                "email" => "kukuh_budi@gmail.com",
                "department_id" => 1,
                "position_id" => 1,
            ],
            [
                "name" => "Asep Suryana",
                "employee_id" => "31100005",
                "email" => "asep_suryana@gmail.com",
                "department_id" => 1,
                "position_id" => 3,
            ],
            [
                "name" => "Maruba Sinaga",
                "employee_id" => "31100186",
                "email" => "maruba_sinaga@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Joko Haryanto",
                "employee_id" => "31100175",
                "email" => "joko_haryanto@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Nanang Purwanto",
                "employee_id" => "31100188",
                "email" => "nanang_purwanto@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Yanuar Cholis",
                "employee_id" => "31612016",
                "email" => "yanuar_cholis@gmail.com",
                "department_id" => 1,
                "position_id" => 1,
            ],
            [
                "name" => "Agus S",
                "employee_id" => "31612012",
                "email" => "agus_s@gmail.com",
                "department_id" => 1,
                "position_id" => 1,
            ],
            [
                "name" => "Muhammad Ridwan",
                "employee_id" => "31100182",
                "email" => "muhammad_ridwan@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Abas",
                "employee_id" => "55000002",
                "email" => "abas@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Fiqhy Febtura",
                "employee_id" => "32307001",
                "email" => "fiqhy_febtura@gmail.com",
                "department_id" => 1,
                "position_id" => 4,
            ],
            [
                "name" => "Agam Hermawan",
                "employee_id" => "60000170",
                "email" => "agam_hermawan@gmail.com",
                "department_id" => 1,
                "position_id" => 4,
            ],
            [
                "name" => "Lucky Suwito",
                "employee_id" => "31903006",
                "email" => "lucky_suwito@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Endang",
                "employee_id" => "33000007",
                "email" => "endang@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Miftahul Huda",
                "employee_id" => "35200119",
                "email" => "miftahul_huda@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Aceng Samsul Romli",
                "employee_id" => "32100031",
                "email" => "aceng_samsul_romli@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Arwan Faisal",
                "employee_id" => "31708079",
                "email" => "arwan_faisal@gmail.com",
                "department_id" => 1,
                "position_id" => 3,
            ],
            [
                "name" => "Saepul Hamdani",
                "employee_id" => "60000134",
                "email" => "saepul_hamdani@gmail.com",
                "department_id" => 1,
                "position_id" => 1,
            ],
            [
                "name" => "Ichsan Fadillah",
                "employee_id" => "72000019",
                "email" => "ichsan_fadillah@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Gunanto",
                "employee_id" => "31905037",
                "email" => "gunanto@gmail.com",
                "department_id" => 1,
                "position_id" => 1,
            ],
            [
                "name" => "Riyanta",
                "employee_id" => "31100034",
                "email" => "riyanta@gmail.com",
                "department_id" => 1,
                "position_id" => 3,
            ],
            [
                "name" => "Arief Darmanto",
                "employee_id" => "72000007",
                "email" => "arief_darmanto@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Yulianto",
                "employee_id" => "31100058",
                "email" => "yulianto@gmail.com",
                "department_id" => 1,
                "position_id" => 3,
            ],
            [
                "name" => "Budiono",
                "employee_id" => "32100029",
                "email" => "budiono@gmail.com",
                "department_id" => 1,
                "position_id" => 2,
            ],
            [
                "name" => "Agung Setiabudi",
                "employee_id" => "60000034",
                "email" => "agung_setiabudi@gmail.com",
                "department_id" => 1,
                "position_id" => 3,
            ],
            [
                "name" => "Didi Priyanto",
                "employee_id" => "31905044",
                "email" => "didi_priyanto@gmail.com",
                "department_id" => 1,
                "position_id" => 1,
            ],
            [
                "name" => "Rosiman Wiraswasta",
                "employee_id" => "60000139",
                "email" => "rosiman_wiraswasta@gmail.com",
                "department_id" => 2,
                "position_id" => 5,
            ],
            [
                "name" => "Nopriadi Saputra",
                "employee_id" => "32210001",
                "email" => "nopriadi_saputra@gmail.com",
                "department_id" => 2,
                "position_id" => 4,
            ],
            [
                "name" => "Erry Puji Anggoro",
                "employee_id" => "55000071",
                "email" => "erry_puji_anggoro@gmail.com",
                "department_id" => 2,
                "position_id" => 3,
            ],
            [
                "name" => "Saiful Bahri",
                "employee_id" => "55000093",
                "email" => "saiful_bahri@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "R. Much Arief S",
                "employee_id" => "55000092",
                "email" => "r._much_arief_s@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Abdul Malik",
                "employee_id" => "31811028",
                "email" => "abdul_malik@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Doni Darmawan",
                "employee_id" => "55000154",
                "email" => "doni_darmawan@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Suryanto",
                "employee_id" => "31100156",
                "email" => "suryanto@gmail.com",
                "department_id" => 2,
                "position_id" => 3,
            ],
            [
                "name" => "Darminto",
                "employee_id" => "31100171",
                "email" => "darminto@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Edi Supriadi",
                "employee_id" => "55000135",
                "email" => "edi_supriadi@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Sartika",
                "employee_id" => "31100107",
                "email" => "sartika@gmail.com",
                "department_id" => 2,
                "position_id" => 3,
            ],
            [
                "name" => "Jaka Kumoro",
                "employee_id" => "31804008",
                "email" => "jaka_kumoro@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Andi Kurnia M",
                "employee_id" => "31804007",
                "email" => "andi_kurnia_m@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Arief Sunari",
                "employee_id" => "31100003",
                "email" => "arief_sunari@gmail.com",
                "department_id" => 2,
                "position_id" => 3,
            ],
            [
                "name" => "Agung Setiawan",
                "employee_id" => "31905034",
                "email" => "agung_setiawan@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Yuda Septiawan",
                "employee_id" => "31905051",
                "email" => "yuda_septiawan@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Arief Rahman",
                "employee_id" => "55000125",
                "email" => "arief_rahman@gmail.com",
                "department_id" => 2,
                "position_id" => 3,
            ],
            [
                "name" => "Denis Capirosi",
                "employee_id" => "31907048",
                "email" => "denis_capirosi@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Aldi Hermawan",
                "employee_id" => "31905052",
                "email" => "aldi_hermawan@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Yopi Sofyan",
                "employee_id" => "60000158",
                "email" => "yopi_sofyan@gmail.com",
                "department_id" => 2,
                "position_id" => 4,
            ],
            [
                "name" => "Rochmad",
                "employee_id" => "31100035",
                "email" => "rochmad@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Naufal Bima A",
                "employee_id" => "31905048",
                "email" => "naufal_bima_a@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Nuri Dwi Karsa",
                "employee_id" => "31812027",
                "email" => "nauri_dwi_karsa@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Gilang Gemuruh Y",
                "employee_id" => "60000144",
                "email" => "gilang_gemuruh_y@gmail.com",
                "department_id" => 2,
                "position_id" => 4,
            ],
            [
                "name" => "Agus Yuanto",
                "employee_id" => "55000099",
                "email" => "agus_yuanto@gmail.com",
                "department_id" => 2,
                "position_id" => 3,
            ],
            [
                "name" => "Johan Gus Zali",
                "employee_id" => "31804024",
                "email" => "johan_gus_zali@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Hendra Wijaya",
                "employee_id" => "60000067",
                "email" => "hendra_wijaya@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Suhadi Lesmana",
                "employee_id" => "55000097",
                "email" => "suhadi_lesmana@gmail.com",
                "department_id" => 2,
                "position_id" => 3,
            ],
            [
                "name" => "Andreas Rio A",
                "employee_id" => "31909064",
                "email" => "andreas_rio_a@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Andriyanto",
                "employee_id" => "31702025",
                "email" => "andriyanto@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Suhaimi",
                "employee_id" => "31100099",
                "email" => "suhaimi@gmail.com",
                "department_id" => 2,
                "position_id" => 3,
            ],
            [
                "name" => "Andreas Hendri K",
                "employee_id" => "31909032",
                "email" => "andreas_hendri_k@gmail.com",
                "department_id" => 2,
                "position_id" => 3,
            ],
            [
                "name" => "Freddy Indra",
                "employee_id" => "31902012",
                "email" => "freddy_indra@gmail.com",
                "department_id" => 2,
                "position_id" => 2,
            ],
            [
                "name" => "Adies Fariedsi",
                "employee_id" => "60000111",
                "email" => "adies_fariedsi@gmail.com",
                "department_id" => 3,
                "position_id" => 4,
            ],
            [
                "name" => "M. Amron Amirul",
                "employee_id" => "31100178",
                "email" => "m._amron_amirul@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "A. Luqmanul Hakim",
                "employee_id" => "55000075",
                "email" => "a._luqmanul_hakim@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "Mujiyanto",
                "employee_id" => "31100113",
                "email" => "mujiyanto@gmail.com",
                "department_id" => 3,
                "position_id" => 2,
            ],
            [
                "name" => "Aditya Dwi Rachmanto",
                "employee_id" => "31708058",
                "email" => "aditya_dwi_rachmanto@gmail.com",
                "department_id" => 3,
                "position_id" => 2,
            ],
            [
                "name" => "Beni Juliana M",
                "employee_id" => "55000079",
                "email" => "beni_juliana_m@gmail.com",
                "department_id" => 3,
                "position_id" => 2,
            ],
            [
                "name" => "Haryanto",
                "employee_id" => "31100172",
                "email" => "haryanto@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "Rianto Pasaribu",
                "employee_id" => "31709017",
                "email" => "rianto_pasaribu@gmail.com",
                "department_id" => 3,
                "position_id" => 2,
            ],
            [
                "name" => "Waliyadin",
                "employee_id" => "31609015",
                "email" => "waliyadin@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "Taufik Nugraha",
                "employee_id" => "31905053",
                "email" => "taufik_nugraha@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Hafidz",
                "employee_id" => "31802014",
                "email" => "hafidz@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Lili",
                "employee_id" => "31100160",
                "email" => "lili@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "Fauzan Abdilah",
                "employee_id" => "31804006",
                "email" => "fauzan_abdilah@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Teguh Purwanto",
                "employee_id" => "31804009",
                "email" => "teguh_purwanto@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Dedy Indra Gunawan",
                "employee_id" => "31611021",
                "email" => "dedy_indra_gunawan@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "Didin Fardi R",
                "employee_id" => "60000142",
                "email" => "didin_fardi_r@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Sunandar",
                "employee_id" => "31802016",
                "email" => "sunandar@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Indra Gunawan",
                "employee_id" => "31910002",
                "email" => "indra_gunawan@gmail.com",
                "department_id" => 3,
                "position_id" => 5,
            ],
            [
                "name" => "Wildan Ardiyansyah",
                "employee_id" => "60000105",
                "email" => "wildan_ardiyansyah@gmail.com",
                "department_id" => 3,
                "position_id" => 4,
            ],
            [
                "name" => "Hario Wibowo",
                "employee_id" => "60000138",
                "email" => "hario_wibowo@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "Akbar Aprianto",
                "employee_id" => "31703017",
                "email" => "akbar_aprianto@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Rasikun",
                "employee_id" => "60000176",
                "email" => "rasikun@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Solihin",
                "employee_id" => "60000135",
                "email" => "solihin@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Narendra Rahman",
                "employee_id" => "31903029",
                "email" => "narendra_rahman@gmail.com",
                "department_id" => 3,
                "position_id" => 2,
            ],
            [
                "name" => "Amin Sugiharto",
                "employee_id" => "72000012",
                "email" => "amin_sugiharto@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "Abdullah",
                "employee_id" => "31706010",
                "email" => "abdullah@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Agus Suripno",
                "employee_id" => "31708057",
                "email" => "agus_suripno@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "Danung Wicaksono",
                "employee_id" => "31609025",
                "email" => "danung_wicaksono@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "Denny Lutfi F B",
                "employee_id" => "31703039",
                "email" => "denny_lutfi_f_b@gmail.com",
                "department_id" => 3,
                "position_id" => 2,
            ],
            [
                "name" => "Bisma Tri Mukti",
                "employee_id" => "31909023",
                "email" => "bisma_tri_mukti@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Triono",
                "employee_id" => "60000165",
                "email" => "triono@gmail.com",
                "department_id" => 3,
                "position_id" => 3,
            ],
            [
                "name" => "Heriwanto",
                "employee_id" => "60000127",
                "email" => "heriwanto@gmail.com",
                "department_id" => 3,
                "position_id" => 2,
            ],
            [
                "name" => "Muh Dikta",
                "employee_id" => "31905050",
                "email" => "muh_dikta@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Ari Wahyu Wibowo",
                "employee_id" => "60000145",
                "email" => "ari_wahyu_wibowo@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Aden",
                "employee_id" => "31704009",
                "email" => "aden@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Ilham Mugniwara",
                "employee_id" => "31905047",
                "email" => "ilham_mugniwara@gmail.com",
                "department_id" => 3,
                "position_id" => 1,
            ],
            [
                "name" => "Bisma Yustiawan",
                "employee_id" => "31809016",
                "email" => "bisma_yustiawan@gmail.com",
                "department_id" => 4,
                "position_id" => 5,
            ],
            [
                "name" => "Rusdi",
                "employee_id" => "31100037",
                "email" => "rusdi@gmail.com",
                "department_id" => 4,
                "position_id" => 4,
            ],
            [
                "name" => "Edo Maheswara",
                "employee_id" => "31811051",
                "email" => "edo_maheswara@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Karsa",
                "employee_id" => "31100109",
                "email" => "karsa@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Nurman Cahyadi P",
                "employee_id" => "55000150",
                "email" => "nurman_cahyadi_p@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Luki Tri Rahman",
                "employee_id" => "55000130",
                "email" => "luki_tri_rahman@gmail.com",
                "department_id" => 4,
                "position_id" => 3,
            ],
            [
                "name" => "Purwanto",
                "employee_id" => "31100177",
                "email" => "purwanto@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Jodi Prastowo",
                "employee_id" => "55000129",
                "email" => "jodi_prastowo@gmail.com",
                "department_id" => 4,
                "position_id" => 3,
            ],
            [
                "name" => "Muhammad Aji Sanjaya",
                "employee_id" => "31702024",
                "email" => "muhammad_aji_sanjaya@gmail.com",
                "department_id" => 4,
                "position_id" => 1,
            ],
            [
                "name" => "Hardono",
                "employee_id" => "31905057",
                "email" => "hardono@gmail.com",
                "department_id" => 4,
                "position_id" => 1,
            ],
            [
                "name" => "Suwaji",
                "employee_id" => "31100075",
                "email" => "suwaji@gmail.com",
                "department_id" => 4,
                "position_id" => 4,
            ],
            [
                "name" => "Haryadi",
                "employee_id" => "31705012",
                "email" => "haryadi@gmail.com",
                "department_id" => 4,
                "position_id" => 3,
            ],
            [
                "name" => "Aditya Pamungkas",
                "employee_id" => "31909022",
                "email" => "aditya_pamungkas@gmail.com",
                "department_id" => 4,
                "position_id" => 1,
            ],
            [
                "name" => "Muhammad Sulistyo",
                "employee_id" => "31907074",
                "email" => "muhammad_sulistyo@gmail.com",
                "department_id" => 4,
                "position_id" => 1,
            ],
            [
                "name" => "Faisal Aziz",
                "employee_id" => "60000180",
                "email" => "faisal_aziz@gmail.com",
                "department_id" => 4,
                "position_id" => 1,
            ],
            [
                "name" => "Dedi Suwandi",
                "employee_id" => "60000025",
                "email" => "dedi_suwandi@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Mulyadi",
                "employee_id" => "31100027",
                "email" => "mulyadi@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Jaelani",
                "employee_id" => "55000136",
                "email" => "jaelani@gmail.com",
                "department_id" => 4,
                "position_id" => 1,
            ],
            [
                "name" => "Haris Wahyudi",
                "employee_id" => "31100017",
                "email" => "haris_wahyudi@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Hendy S",
                "employee_id" => "31703016",
                "email" => "hendy_s@gmail.com",
                "department_id" => 4,
                "position_id" => 1,
            ],
            [
                "name" => "Udi Samyono",
                "employee_id" => "32100017",
                "email" => "udi_samyono@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Wagi",
                "employee_id" => "4710014",
                "email" => "wagi@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Tri Eko S",
                "employee_id" => "55000148",
                "email" => "tri_eko_s@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Obos",
                "employee_id" => "31100031",
                "email" => "obos@gmail.com",
                "department_id" => 4,
                "position_id" => 3,
            ],
            [
                "name" => "Franciscus Bagus T",
                "employee_id" => "31909066",
                "email" => "franciscus_bagus_t@gmail.com",
                "department_id" => 4,
                "position_id" => 2,
            ],
            [
                "name" => "Weerasak Pintong",
                "employee_id" => "11111111",
                "email" => "weerasak_pintong@gmail.com",
                "department_id" => 5,
                "position_id" => 6,
            ],
            [
                "name" => "Manickam Arumugam",
                "employee_id" => "31904038",
                "email" => "manickam_arumugam@gmail.com",
                "department_id" => 5,
                "position_id" => 4,
            ],
            [
                "name" => "Hadi Yulianto",
                "employee_id" => "32209003",
                "email" => "hadi_yulianto@gmail.com",
                "department_id" => 5,
                "position_id" => 4,
            ],
            [
                "name" => "Nachtiar",
                "employee_id" => "31100064",
                "email" => "nachtiar@gmail.com",
                "department_id" => 5,
                "position_id" => 2,
            ],
            [
                "name" => "Christofan",
                "employee_id" => "31100174",
                "email" => "christofan@gmail.com",
                "department_id" => 5,
                "position_id" => 2,
            ],
            [
                "name" => "Emus Mulyadi",
                "employee_id" => "31910007",
                "email" => "emus_mulyadi@gmail.com",
                "department_id" => 5,
                "position_id" => 3,
            ],
            [
                "name" => "Asep Rudiatuloh",
                "employee_id" => "31708067",
                "email" => "asep_rudiatuloh@gmail.com",
                "department_id" => 5,
                "position_id" => 2,
            ],
            [
                "name" => "Gilang Irawan",
                "employee_id" => "55000133",
                "email" => "gilang_irawan@gmail.com",
                "department_id" => 5,
                "position_id" => 1,
            ],
            [
                "name" => "Candra Budi W",
                "employee_id" => "32207011",
                "email" => "candra_budi_w@gmail.com",
                "department_id" => 5,
                "position_id" => 2,
            ],
            [
                "name" => "Totok Budiyanto",
                "employee_id" => "31811029",
                "email" => "totok_budiyanto@gmail.com",
                "department_id" => 5,
                "position_id" => 2,
            ],
            [
                "name" => "Adih S",
                "employee_id" => "46200060",
                "email" => "adih_s@gmail.com",
                "department_id" => 5,
                "position_id" => 2,
            ],
            [
                "name" => "Muslim",
                "employee_id" => "31100029",
                "email" => "muslim@gmail.com",
                "department_id" => 5,
                "position_id" => 4,
            ],
            [
                "name" => "Dedi Saputra",
                "employee_id" => "31803011",
                "email" => "dedi_saputra@gmail.com",
                "department_id" => 5,
                "position_id" => 2,
            ],
            [
                "name" => "Yuan Lucky Prasetyo",
                "employee_id" => "31903007",
                "email" => "yuan_lucky_prasetyo@gmail.com",
                "department_id" => 5,
                "position_id" => 2,
            ],
            [
                "name" => "Henri Valudi",
                "employee_id" => "33000061",
                "email" => "henri_valudi@gmail.com",
                "department_id" => 6,
                "position_id" => 5,
            ],
            [
                "name" => "Ignatius Tulus",
                "employee_id" => "33000091",
                "email" => "ignatius_tulus@gmail.com",
                "department_id" => 6,
                "position_id" => 4,
            ],
            [
                "name" => "Antonius Hari Budi P",
                "employee_id" => "33000115",
                "email" => "antonius_hari_budi_p@gmail.com",
                "department_id" => 6,
                "position_id" => 4,
            ],
            [
                "name" => "Yesa Firmanta Benictus",
                "employee_id" => "33000191",
                "email" => "yesa_firmanta_benictus@gmail.com",
                "department_id" => 6,
                "position_id" => 3,
            ],
            [
                "name" => "Budi Budianto",
                "employee_id" => "31708039",
                "email" => "budi_budianto@gmail.com",
                "department_id" => 6,
                "position_id" => 3,
            ],
            [
                "name" => "Akhbar Karismawan M",
                "employee_id" => "31708045",
                "email" => "akhbar_karismawan_m@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Yosua Kurniawan S P",
                "employee_id" => "32007011",
                "email" => "yosua_kurniawan_s_p@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Johery Kanes",
                "employee_id" => "33000208",
                "email" => "johery_kanes@gmail.com",
                "department_id" => 6,
                "position_id" => 3,
            ],
            [
                "name" => "Ferico Bobby P",
                "employee_id" => "31910022",
                "email" => "ferico_bobby_p@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Rahmat Hidayat",
                "employee_id" => "33000161",
                "email" => "rahmat_hidayat@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Agung Ginanjar",
                "employee_id" => "33000172",
                "email" => "agung_ginanjar@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Aswin Reza Bakhtiar",
                "employee_id" => "33000167",
                "email" => "aswin_reza_bakhtiar@gmail.com",
                "department_id" => 6,
                "position_id" => 3,
            ],
            [
                "name" => "Winfritz Corneilo Sinaga",
                "employee_id" => "31908004",
                "email" => "winfritz_corneilo_sinaga@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Andriyas Wicaksono",
                "employee_id" => "31708046",
                "email" => "andriyas_wicaksono@gmail.com",
                "department_id" => 6,
                "position_id" => 3,
            ],
            [
                "name" => "Sutrisno",
                "employee_id" => "33000210",
                "email" => "sutrisno@gmail.com",
                "department_id" => 6,
                "position_id" => 3,
            ],
            [
                "name" => "Sujana Barkah",
                "employee_id" => "33000146",
                "email" => "sujana_barkah@gmail.com",
                "department_id" => 6,
                "position_id" => 4,
            ],
            [
                "name" => "Jamal Mirdad",
                "employee_id" => "55000153",
                "email" => "jamal_mirdad@gmail.com",
                "department_id" => 6,
                "position_id" => 4,
            ],
            [
                "name" => "Dimas Bagusing P",
                "employee_id" => "31701003",
                "email" => "dimas_bagusing_p@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Muhammad Rafi",
                "employee_id" => "33000205",
                "email" => "muhammad_rafi@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Suprihatin",
                "employee_id" => "31903034",
                "email" => "suprihatin@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Abdan S",
                "employee_id" => "32207007",
                "email" => "abdan_s@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Franciscus Intan Prakoso",
                "employee_id" => "33000185",
                "email" => "franciscus_intan_prakoso@gmail.com",
                "department_id" => 6,
                "position_id" => 3,
            ],
            [
                "name" => "Shuhuf Kholisdianto",
                "employee_id" => "33000181",
                "email" => "shuhuf_kholisdianto@gmail.com",
                "department_id" => 6,
                "position_id" => 3,
            ],
            [
                "name" => "Rizal Prasetya Nugraha",
                "employee_id" => "31902002",
                "email" => "rizal_prasetya_nugraha@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Rangga Pratama",
                "employee_id" => "33000180",
                "email" => "rangga_pratama@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Romy Maryurisben",
                "employee_id" => "33000183",
                "email" => "romy_maryurisben@gmail.com",
                "department_id" => 6,
                "position_id" => 3,
            ],
            [
                "name" => "Donie Winata",
                "employee_id" => "31907080",
                "email" => "donie_winata@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Budi Utomo",
                "employee_id" => "33002002",
                "email" => "budi_utomo@gmail.com",
                "department_id" => 6,
                "position_id" => 2,
            ],
            [
                "name" => "Supriyanto",
                "employee_id" => "33000204",
                "email" => "supriyanto@gmail.com",
                "department_id" => 6,
                "position_id" => 3,
            ],
        ];

        collect($electricians)->each(fn($e) => User::create([
            "password" => Hash::make("password"),
            "name" => Str::apa($e["name"]),
            ...$e
        ]));
    }
}
